In [2]:
!pip install --upgrade category_encoders

Requirement already satisfied: category_encoders in /srv/conda/envs/notebook/lib/python3.6/site-packages (2.3.0)
Requirement already satisfied: patsy>=0.5.1 in /srv/conda/envs/notebook/lib/python3.6/site-packages (from category_encoders) (0.5.2)
Requirement already satisfied: scikit-learn>=0.20.0 in /srv/conda/envs/notebook/lib/python3.6/site-packages (from category_encoders) (0.24.2)
Requirement already satisfied: pandas>=0.21.1 in /srv/conda/envs/notebook/lib/python3.6/site-packages (from category_encoders) (1.1.5)
Requirement already satisfied: statsmodels>=0.9.0 in /srv/conda/envs/notebook/lib/python3.6/site-packages (from category_encoders) (0.12.2)
Requirement already satisfied: numpy>=1.14.0 in /srv/conda/envs/notebook/lib/python3.6/site-packages (from category_encoders) (1.19.5)
Requirement already satisfied: scipy>=1.0.0 in /srv/conda/envs/notebook/lib/python3.6/site-packages (from category_encoders) (1.5.3)
Requirement already satisfied: python-dateutil>=2.7.3 in /srv/conda/envs/notebook/lib/python3.6/site-packages (from pandas>=0.21.1->category_encoders) (2.8.2)
Requirement already satisfied: pytz>=2017.2 in /srv/conda/envs/notebook/lib/python3.6/site-packages (from pandas>=0.21.1->category_encoders) (2021.3)
Requirement already satisfied: six in /srv/conda/envs/notebook/lib/python3.6/site-packages (from patsy>=0.5.1->category_encoders) (1.16.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /srv/conda/envs/notebook/lib/python3.6/site-packages (from scikit-learn>=0.20.0->category_encoders) (3.0.0)
Requirement already satisfied: joblib>=0.11 in /srv/conda/envs/notebook/lib/python3.6/site-packages (from scikit-learn>=0.20.0->category_encoders) (1.1.0)

In [3]:
#import required libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import category_encoders as ce 
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import recall_score, precision_score, accuracy_score, plot_confusion_matrix, classification_report, f1_score

In [4]:
df=pd.read_csv('ChurnData.csv')
df.head()

,tenure,age,address,income,ed,employ,equip,callcard,wireless,longmon,...,pager,internet,callwait,confer,ebill,loglong,logtoll,lninc,custcat,churn
0,11,33,7,136,5,5,0,1,1,4.40,...,1,0,1,1,0,1.482,3.033,4.913,4,1
1,33,33,12,33,2,0,0,0,0,9.45,...,0,0,0,0,0,2.246,3.240,3.497,1,1
2,23,30,9,30,1,2,0,0,0,6.30,...,0,0,0,1,0,1.841,3.240,3.401,3,0
3,38,35,5,76,2,10,1,1,1,6.05,...,1,1,1,1,1,1.800,3.807,4.331,4,0
4,7,35,14,80,2,15,0,1,0,7.10,...,0,0,1,1,0,1.960,3.091,4.382,3,0

In [6]:
col_names= ['tenure','age','address','income','ed','employ','equip','callcard','wireless','longmon','tollmon','equipmon','cardmon','wiremon','longten','tollten'
,'cardten','voice','pager','internet','callwait','confer','ebill','longlong','longtoll','lninc','custcat','churn']
df.columns = col_names
df.head()

,tenure,age,address,income,ed,employ,equip,callcard,wireless,longmon,...,pager,internet,callwait,confer,ebill,longlong,longtoll,lninc,custcat,churn
0,11,33,7,136,5,5,0,1,1,4.40,...,1,0,1,1,0,1.482,3.033,4.913,4,1
1,33,33,12,33,2,0,0,0,0,9.45,...,0,0,0,0,0,2.246,3.240,3.497,1,1
2,23,30,9,30,1,2,0,0,0,6.30,...,0,0,0,1,0,1.841,3.240,3.401,3,0
3,38,35,5,76,2,10,1,1,1,6.05,...,1,1,1,1,1,1.800,3.807,4.331,4,0
4,7,35,14,80,2,15,0,1,0,7.10,...,0,0,1,1,0,1.960,3.091,4.382,3,0

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 28 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   tenure    200 non-null    int64
 1   age       200 non-null    int64
 2   address   200 non-null    int64
 3   income    200 non-null    int64
 4   ed        200 non-null    int64
 5   employ    200 non-null    int64
 6   equip     200 non-null    int64
 7   callcard  200 non-null    int64
 8   wireless  200 non-null    int64
 9   longmon   200 non-null    float64
 10  tollmon   200 non-null    float64
 11  equipmon  200 non-null    float64
 12  cardmon   200 non-null    float64
 13  wiremon   200 non-null    float64
 14  longten   200 non-null    float64
 15  tollten   200 non-null    float64
 16  cardten   200 non-null    float64
 17  voice     200 non-null    int64
 18  pager     200 non-null    int64
 19  internet  200 non-null    int64
 20  callwait  200 non-null    int64
 21  confer    200 non-null    int64
 22  ebill     200 non-null    int64
 23  longlong  200 non-null    float64
 24  longtoll  200 non-null    float64
 25  lninc     200 non-null    float64
 26  custcat   200 non-null    int64
 27  churn     200 non-null    int64
dtypes: float64(11), int64(17)
memory usage: 43.9 KB

In [8]:
def show(data):
  for i in df.columns[1:]:
    print("Feature: {} with {} Levels".format(i,data[i].unique()))

show(df)

Feature: age with [33 30 35 52 40 21 50 51 27 61 25 24 54 22 37 42 43 47 26 55 34 69 65 29
 57 66 56 58 39 64 36 60 45 76 31 59 46 62 44 23 32 63 48 41 28 75 53 19
 20 38 49] Levels
Feature: address with [ 7 12  9  5 14 17  1 26 27 28 16 11  3  4  2 23 13  6 18 25 43 33 10 34
 15 32 38 21 20  0 22 19 30  8 29 48 37 35 31 24] Levels
Feature: income with [ 136   33   30   76   80  120   37   17  140   63   49  127  438  161
   53   19   41   31   36   24   25  131  101  108   20  123   34  104
   46   57   58  128   26   23   52   55   40   42  144   82  102  170
   96   64   18    9   91   67   93  117   65   28   38   59   39   12
   27   21 1668   66   44   83  197   68   69   35   60  135   88   48
   78  263   73  151   75   14   22   43   51  147  163   71  129   47
   72   45   89  398  171   61   50   70  119   11  107  100  201   56
  333  288  190] Levels
Feature: ed with [5 2 1 4 3] Levels
Feature: employ with [ 5  0  2 10 15 24  8 21 19 12 23  6 11  1  3 22  9  7 26  4 18 16 13 30
 17 20 27 28 33 29 44 31 37 14 25] Levels
Feature: equip with [0 1] Levels
Feature: callcard with [1 0] Levels
Feature: wireless with [1 0] Levels
Feature: longmon with [ 4.4   9.45  6.3   6.05  7.1  20.7   8.25  2.9   6.5  12.85 24.75 19.7
 28.8  29.    6.    3.4  12.25 24.05  4.    9.6   5.85  9.95  2.   12.05
  5.8  13.65 21.8   3.35  2.5  15.    7.5   6.35 21.2  10.4   3.7  14.25
  9.1   4.5   7.7  11.95  7.6   8.8   7.75  4.05 16.3  14.2  12.5   8.5
  8.65  3.85  2.7   5.15  3.8   4.3   5.5  14.05 18.85 12.4  26.7  10.95
 16.85 18.1  53.75 25.05 12.9  19.65 12.65  8.2  21.85 13.35  7.    4.65
  7.25  8.55  7.9  45.4   3.2   3.65  5.25  8.    8.3   7.05  4.15 19.2
 17.25 17.65  1.1   6.85 14.3  11.9   9.55  7.55  3.55  7.35 13.9  33.65
  2.95  3.75  7.65  4.7  32.65  6.2   3.3   8.95 37.3  27.    5.05 49.3
 10.5   6.95 28.35  6.55  1.8   6.1  34.25 20.35 14.95 13.45 25.6   4.2
 43.6  10.6   5.55  6.4  29.2   9.9   5.4  25.95  5.9   6.15 16.15 15.25
 10.8  27.35  6.45 20.55 34.95  4.1   5.95  2.75 22.05  9.2  17.3  14.15
 62.3  15.7   4.25  4.55 16.4  10.55 10.3  30.9   1.9  12.1  16.1  17.35
  8.7 ] Levels
Feature: tollmon with [20.75  0.   45.   22.   23.5  27.5  25.75 55.5  23.75 24.75 14.75 27.25
 22.5  30.25 24.   40.75 17.   55.   27.   23.   21.25 30.   16.   28.
 42.75  9.   23.25 68.5  39.   35.   28.25 31.   15.   18.5  26.5  25.5
 21.75  9.5  32.25 25.25 28.5   5.75 19.5  41.   24.5  21.5  48.25 31.75
 32.75 21.   29.   37.   15.75 18.   52.   58.75 19.   19.25 28.75 15.25
 14.   25.   18.75 38.25 47.75] Levels
Feature: equipmon with [ 0.   50.1  36.9  28.15 47.05 49.8  39.4  38.4  35.4  26.15 27.15 35.35
 42.   25.3  23.4  33.9  53.95 48.4  36.2  30.95 31.45 33.35 33.05 32.7
 25.55 32.8  32.1  42.65 25.1  32.   51.7  27.2  56.8  48.3  24.5  32.55
 39.75 25.25 35.2  25.75 21.6  41.55 29.9  52.   22.8  36.05 39.6  59.2
 31.95 23.25 39.65 43.7  42.4  30.3  24.3  21.95 62.15 45.15 62.4  32.35
 50.25 39.25 33.   40.4  40.3  43.1  28.95 24.95 45.4  35.05 57.45 63.25
 38.35 39.15 35.1  26.55 29.5  30.45 34.2  35.65 29.2  42.55] Levels
Feature: cardmon with [ 15.25   0.    23.25  23.75  22.    28.    35.    14.25  22.25  14.75
  21.25  24.75   8.75  27.25   9.5    6.5   20.75   8.     9.25  13.75
  16.    39.25  11.75  14.5   12.5   21.    19.25  48.    23.    13.
  10.25  30.     8.5    6.75   3.75  42.75  19.5   20.5   28.25  12.25
  18.5    6.25  35.25  32.75   5.75  14.    19.75  16.5    9.75  46.5
  25.25  32.5   15.5   27.5   46.75   7.    18.25  31.75  20.25  18.
  17.75  41.     2.75   8.25  15.75  10.     4.5    7.25  41.75  40.
 109.25  33.    26.    39.75  17.    31.    20.    13.5   12.75  34.
  18.75  28.5   37.75  13.25  36.    17.5    7.5   65.25  12.    16.75
  55.5   26.5 ] Levels
Feature: wiremon with [ 35.7    0.    64.9   37.4   61.1   35.75  35.95  21.65  63.    50.6
  33.4   85.85  23.35  37.9   19.65  41.3   52.9   43.95  51.    43.5
  25.4   50.85  26.1   19.45  36.6   47.    28.55  28.95  35.4   79.2
  21.9   26.4   20.8   38.8   36.3   28.15  83.7   56.55  47.8   55.9
  23.4   43.05  47.7   37.25  67.   109.7   17.7   31.8   29.15  59.55
  24.95  37.7   27.05  57.05  23.65  64.    44.1 ] Levels
Feature: longten with [4.20000e+01 2.88800e+02 1.57050e+02 2.39550e+02 4.74500e+01 1.39105e+03
 3.99150e+02 2.52500e+01 2.47550e+02 5.85600e+02 1.34905e+03 9.09900e+02
 1.55810e+03 1.81540e+03 8.07000e+01 1.03500e+01 1.76200e+02 6.31700e+02
 1.53655e+03 4.60000e+01 3.53550e+02 9.70000e+01 4.12100e+02 3.05000e+00
 6.66000e+02 1.03100e+02 8.17650e+02 1.29200e+03 7.55000e+00 9.25000e+00
 1.98700e+02 9.60950e+02 1.25050e+02 2.26250e+02 1.18050e+02 1.32505e+03
 4.03500e+02 9.19500e+01 6.11650e+02 4.22700e+02 8.91000e+01 3.63950e+02
 6.16250e+02 3.34450e+02 3.05750e+02 3.38800e+02 7.15000e+01 6.46700e+02
 1.00120e+03 7.10800e+02 2.98250e+02 2.10600e+02 5.50500e+01 1.67650e+02
 2.70000e+00 1.10550e+02 5.28500e+01 1.75500e+01 1.89050e+02 1.87400e+02
 1.20070e+03 7.55700e+02 1.87425e+03 3.51000e+01 4.12800e+02 8.88450e+02
 2.73700e+02 1.11475e+03 1.48750e+02 3.77610e+03 1.54190e+03 6.60850e+02
 3.63650e+02 1.00880e+03 5.58850e+02 5.04300e+02 3.03950e+02 1.58910e+03
 3.14800e+02 7.09250e+02 3.21950e+02 1.23000e+01 5.93000e+01 1.71850e+02
 2.15950e+02 2.53050e+02 2.97355e+03 2.45500e+01 2.10000e+01 1.47950e+02
 6.15500e+01 3.08550e+02 1.53050e+02 4.00550e+02 4.63500e+01 9.64850e+02
 1.60400e+02 1.04570e+03 9.50700e+02 1.10000e+00 1.06500e+02 4.59050e+02
 5.24250e+02 3.55000e+01 3.75400e+02 1.56150e+02 1.97000e+01 2.17450e+02
 5.56200e+02 1.87120e+03 2.15500e+01 5.97500e+01 1.40850e+02 7.52500e+01
 2.63000e+01 2.41260e+03 3.47000e+01 1.86500e+02 1.77400e+02 9.90000e+00
 4.59500e+01 8.86500e+01 4.85500e+01 4.92350e+02 2.68625e+03 1.72250e+03
 5.99500e+01 3.69450e+02 3.07750e+02 3.41740e+03 2.67600e+02 4.29100e+02
 9.85000e+01 6.95200e+02 2.01760e+03 9.74000e+01 5.03500e+01 3.15200e+02
 2.71000e+01 6.38000e+01 2.29825e+03 1.26390e+03 9.74150e+02 5.83900e+02
 1.75960e+03 3.04080e+03 2.67300e+02 6.51500e+01 2.39000e+01 7.10000e+01
 1.33100e+02 1.72660e+03 6.08650e+02 2.91500e+02 7.12000e+01 1.20350e+02
 1.81215e+03 4.89500e+01 1.18150e+02 9.65300e+02 8.73700e+02 6.34750e+02
 1.98015e+03 1.04050e+02 1.40715e+03 2.66500e+01 2.50605e+03 2.71550e+02
 6.24500e+01 8.04000e+02 3.77000e+01 7.33500e+01 5.70000e+00 5.56500e+02
 6.27500e+01 1.04295e+03 3.47100e+02 8.40000e+02 7.52900e+02 4.33300e+03
 2.37850e+02 8.15050e+02 1.02450e+02 2.07700e+02 1.15650e+02 9.33100e+02
 2.90250e+02 6.59550e+02 2.12360e+03 1.93000e+01 2.14700e+02 7.51750e+02
 9.38650e+02 9.73100e+02 2.03250e+02 2.99000e+01 1.86600e+02 1.06315e+03] Levels
Feature: tollten with [ 211.45    0.   1873.05  166.1   950.65 1068.25 1278.45 3119.45  103.1
  299.    663.1  1492.1    49.55 1105.75  454.05 1483.55 1802.5   386.8
 2662.1  1840.65 1345.95  567.55  317.5   722.5   317.75  543.15 1721.25
 2921.35   57.8  1250.7  4938.6  2536.1  1919.75  820.15 1661.3   595.6
 1849.5   978.85 1161.3   241.8   688.35  522.15   76.05  612.45  264.
  697.05 1320.05  359.25 1502.2     5.75  616.5  1108.4   502.    872.5
  253.35  404.8   188.35  438.4   420.65  225.85 1959.95 1079.05 2254.15
  357.95 3086.35 2276.3   419.25  531.1  1425.35 1806.85  690.85   62.25
  259.   1231.9  1972.1  2794.95  497.15 3525.55  318.75  127.5  2074.75
  501.15  260.05  179.8    49.65 1280.9   830.75 1396.75  895.05  729.15
  805.85  288.75 2355.4   114.4   822.35 1343.5   959.4   128.45 1152.9 ] Levels
Feature: cardten with [1.250e+02 0.000e+00 8.800e+02 1.450e+02 1.505e+03 1.190e+03 1.215e+03
 6.350e+02 6.800e+02 1.065e+03 1.655e+03 4.650e+02 1.400e+03 2.950e+02
 3.350e+02 1.195e+03 4.250e+02 1.500e+01 4.000e+01 4.900e+02 2.360e+03
 1.750e+02 9.400e+02 4.800e+02 9.850e+02 6.750e+02 3.950e+02 2.330e+03
 7.300e+02 5.650e+02 3.600e+02 2.140e+03 2.600e+02 7.500e+01 9.500e+01
 1.000e+02 2.665e+03 1.135e+03 1.465e+03 1.550e+02 9.950e+02 2.300e+02
 2.200e+03 7.800e+02 1.980e+03 3.150e+02 3.700e+02 1.050e+03 7.600e+02
 4.100e+02 3.265e+03 7.750e+02 9.150e+02 2.200e+02 8.400e+02 3.065e+03
 5.500e+01 8.350e+02 1.150e+03 3.900e+02 4.300e+02 1.085e+03 2.170e+03
 2.750e+00 4.950e+02 3.050e+02 2.100e+02 3.850e+02 1.050e+02 6.000e+02
 1.350e+02 3.500e+01 3.085e+03 1.100e+02 3.400e+02 8.550e+02 7.515e+03
 1.245e+03 8.200e+02 1.835e+03 9.000e+01 2.845e+03 2.750e+02 5.400e+02
 1.400e+02 1.355e+03 1.140e+03 1.020e+03 2.020e+03 5.300e+02 2.500e+01
 6.550e+02 1.070e+03 1.660e+03 1.270e+03 1.950e+02 1.350e+03 1.630e+03
 2.305e+03 8.950e+02 2.400e+02 1.370e+03 2.560e+03 2.900e+02 2.710e+03
 4.500e+02 3.450e+02 1.155e+03 5.600e+02 4.915e+03 5.950e+02 4.000e+02
 3.000e+02 3.650e+02 3.145e+03 7.700e+02 9.750e+02 1.305e+03 9.100e+02
 6.300e+02 7.200e+02 4.350e+02 8.000e+01 1.600e+03] Levels
Feature: voice with [1 0] Levels
Feature: pager with [1 0] Levels
Feature: internet with [0 1] Levels
Feature: callwait with [1 0] Levels
Feature: confer with [1 0] Levels
Feature: ebill with [0 1] Levels
Feature: longlong with [1.482 2.246 1.841 1.8   1.96  3.03  2.11  1.065 1.872 2.553 3.209 2.981
 3.36  3.367 1.792 1.224 2.506 3.18  1.386 2.262 1.766 2.298 0.693 2.489
 1.758 2.614 3.082 1.209 0.916 2.708 2.015 1.848 3.054 2.342 1.308 2.657
 2.208 1.504 2.041 2.481 2.028 2.175 2.048 1.399 2.791 2.653 2.526 2.14
 2.158 1.348 0.993 1.639 1.335 1.459 1.705 2.643 2.937 2.518 3.285 2.393
 2.824 2.896 3.984 3.221 2.557 2.978 2.538 2.104 3.084 2.592 1.946 1.537
 1.981 2.146 2.067 3.816 1.163 1.295 1.658 2.079 2.116 1.953 1.423 2.955
 2.848 2.871 0.095 1.924 2.66  2.477 2.257 2.022 1.267 1.995 2.632 3.516
 1.082 1.322 2.035 1.548 3.486 1.825 1.194 2.192 3.619 3.296 1.619 3.898
 2.351 1.939 3.345 1.879 0.588 1.808 3.534 3.013 2.705 2.599 3.243 1.435
 3.775 2.361 1.714 1.856 3.374 2.293 1.686 3.256 1.775 1.816 2.782 2.725
 2.38  3.309 1.864 3.023 3.554 1.411 1.783 1.012 3.093 2.219 2.851 2.65
 4.132 2.754 1.447 1.515 2.797 2.356 2.332 3.431 0.642 2.493 2.779 2.854
 2.163] Levels
Feature: longtoll with [3.033 3.24  3.807 3.091 3.157 3.314 3.248 4.016 3.168 3.209 2.691 3.305
 3.114 3.409 3.178 3.707 2.833 4.007 3.296 3.135 3.056 3.401 2.773 3.332
 3.755 2.197 3.146 4.227 3.664 3.555 3.341 3.434 2.708 2.918 3.277 3.239
 3.08  2.251 3.474 3.229 3.35  1.749 2.97  3.714 3.199 3.068 3.876 3.458
 3.489 3.045 3.367 3.611 2.757 2.89  3.951 4.073 2.944 2.958 3.359 2.725
 2.639 3.219 2.931 3.644 3.866] Levels
Feature: lninc with [4.913 3.497 3.401 4.331 4.382 4.787 3.611 2.833 4.942 4.143 3.892 4.844
 6.082 5.081 3.97  2.944 3.714 3.434 3.584 3.178 3.219 4.875 4.615 4.682
 2.996 4.812 3.526 4.644 3.829 4.043 4.06  4.852 3.258 3.135 3.951 4.007
 3.689 3.738 4.97  4.407 4.625 5.136 4.564 4.159 2.89  2.197 4.511 4.205
 4.533 4.762 4.174 3.332 3.638 4.078 3.664 2.485 3.296 3.045 7.419 4.19
 3.784 4.419 5.283 4.22  4.234 3.555 4.094 4.905 4.477 3.871 4.357 5.572
 4.29  5.017 4.317 2.639 3.091 3.761 3.932 4.99  5.094 4.263 4.86  3.85
 4.277 3.807 4.489 5.986 5.142 4.111 3.912 4.248 4.779 2.398 4.673 4.605
 5.303 4.025 5.808 5.663 5.247] Levels
Feature: custcat with [4 1 3 2] Levels
Feature: churn with [1 0] Levels

In [9]:
df.isnull().sum()

tenure      0
age         0
address     0
income      0
ed          0
employ      0
equip       0
callcard    0
wireless    0
longmon     0
tollmon     0
equipmon    0
cardmon     0
wiremon     0
longten     0
tollten     0
cardten     0
voice       0
pager       0
internet    0
callwait    0
confer      0
ebill       0
longlong    0
longtoll    0
lninc       0
custcat     0
churn       0
dtype: int64

In [10]:
df.dtypes

tenure        int64
age           int64
address       int64
income        int64
ed            int64
employ        int64
equip         int64
callcard      int64
wireless      int64
longmon     float64
tollmon     float64
equipmon    float64
cardmon     float64
wiremon     float64
longten     float64
tollten     float64
cardten     float64
voice         int64
pager         int64
internet      int64
callwait      int64
confer        int64
ebill         int64
longlong    float64
longtoll    float64
lninc       float64
custcat       int64
churn         int64
dtype: object

In [11]:
# Define x and y
x = df.drop(['churn'], axis = 1)
y = df['churn']
# spilliting dataset into training and testing
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 42)
print("X_train: {}".format(x_train.shape))
print("X_test: {}".format(x_test.shape))
print("Y_train: {}".format(y_train.shape))
print("Y_test: {}".format(y_test.shape))

X_train: (140, 27)
X_test: (60, 27)
Y_train: (140,)
Y_test: (60,)

In [12]:
# Finding accuracy
def evaluation_parametrics(y_train,yp_train,y_test,yp_test):
  print("--------------------------------------------------------------------------")
  print("Classification Report for Train Data")
  print(classification_report(y_train, yp_train))
  print("Classification Report for Test Data")
  print(classification_report(y_test, yp_test))
  print("--------------------------------------------------------------------------")
  # Accuracy
  print("Accuracy on Train Data is: {}".format(round(accuracy_score(y_train,yp_train),2)))
  print("Accuracy on Test Data is: {}".format(round(accuracy_score(y_test,yp_test),2)))
  print("--------------------------------------------------------------------------")
  # Precision
  print("Precision on Train Data is: {}".format(round(precision_score(y_train,yp_train,average = "weighted"),2)))
  print("Precision on Test Data is: {}".format(round(precision_score(y_test,yp_test,average = "weighted"),2)))
  print("--------------------------------------------------------------------------")
  # Recall 
  print("Recall on Train Data is: {}".format(round(recall_score(y_train,yp_train,average = "weighted"),2)))
  print("Recall on Test Data is: {}".format(round(recall_score(y_test,yp_test,average = "weighted"),2)))
  print("--------------------------------------------------------------------------")
  # F1 Score
  print("F1 Score on Train Data is: {}".format(round(f1_score(y_train,yp_train,average = "weighted"),2)))
  print("F1 Score on Test Data is: {}".format(round(f1_score(y_test,yp_test,average = "weighted"),2)))
  print("--------------------------------------------------------------------------")

In [13]:
# Create model random forest
rf = RandomForestClassifier(n_estimators = 50,random_state = 48) # Keeping max_depth = 7 same as DT
rf.fit(x_train,y_train)

yp_train = rf.predict(x_train)
yp_test = rf.predict(x_test)

evaluation_parametrics(y_train,yp_train,y_test,yp_test)

--------------------------------------------------------------------------
Classification Report for Train Data
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        97
           1       1.00      1.00      1.00        43

    accuracy                           1.00       140
   macro avg       1.00      1.00      1.00       140
weighted avg       1.00      1.00      1.00       140

Classification Report for Test Data
              precision    recall  f1-score   support

           0       0.88      0.82      0.85        45
           1       0.56      0.67      0.61        15

    accuracy                           0.78        60
   macro avg       0.72      0.74      0.73        60
weighted avg       0.80      0.78      0.79        60

--------------------------------------------------------------------------
Accuracy on Train Data is: 1.0
Accuracy on Test Data is: 0.78
--------------------------------------------------------------------------
Precision on Train Data is: 1.0
Precision on Test Data is: 0.8
--------------------------------------------------------------------------
Recall on Train Data is: 1.0
Recall on Test Data is: 0.78
--------------------------------------------------------------------------
F1 Score on Train Data is: 1.0
F1 Score on Test Data is: 0.79
--------------------------------------------------------------------------

# End